### ISSUE TITLE
Potential SQL injections/XSS issues

### ISSUE THREAD

**Issue by Fitblip** [joshbooks/OnionDrop#2]
You should really be using an ORM like SQLAlchemy, as 1.) it exposes a better interface (no `select what from where`, you work with classes with well-defined data types instead), and 2.) it protects you from accidentally introducing SQL injections (though right now you appear to be handling SQL correctly), and 3.) It's extremely well supported in flask.

http://flask-sqlalchemy.pocoo.org/2.1/

I suggest also using Jinja2 for all HTML going out, as it'll prevent [XSS](https://www.owasp.org/index.php/Cross-site_Scripting_%28XSS%29) issues like [this](https://github.com/joshbooks/OnionDrop/blob/master/toHSO.py#L475), which may be used to attack your site.

Let me know if you have any questions, and it was a pleasure to meet you today! 

![](https://media.giphy.com/media/BXEu20gFrvGIo/giphy.gif)

**Comment by joshbooks** [comment]
@Fitblip as of [af5770a](https://github.com/joshbooks/OnionDrop/commit/af5770a0de43ba3702708b2a71775f4389aa07af) the XSS issue should be fixed. Any objection to closing this ticket?

**Comment by Fitblip** [comment]
![](https://vignette2.wikia.nocookie.net/p__/images/3/31/Slowpoke.jpg/revision/latest?cb=20131028182656&path-prefix=protagonist)

Yeah this is fine to close, you can also close it yourself :-P
